apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsample
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appsample
  template:
    metadata:
      labels:
        app: appsample
    spec:
      containers:
      - name: appsample
        image: appsample
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: appsample-service
spec:
  type: LoadBalancer
  selector:
    app: appsample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000